<!-- <? xml version="1.0" ?> -->
<robot name="mycamera" xmlns:xacro="https://www.ros.org/wiki/xacro" >
    <xacro:property name="camera_length" value="0.02" />
    <xacro:property name="camera_width" value="0.04" />
    <xacro:property name="camera_height" value="0.03" />
    <xacro:property name="camera_x" value="${base_link_radius - camera_length - 0.01}" />
    <xacro:property name="camera_y" value="0" />
    <xacro:property name="camera_z" value="${base_link_length}" />

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="blue" >
                <color rgba="0 0 1 1" />
            </material>
        </visual>
    </link>

    <joint name="camera2baselink" type="continuous" >
        <parent link="base_link" />
        <child link="camera" />
        <origin xyz="${camera_x} ${camera_y} ${camera_z}" />
        <axis xyz="0 0 1" />
    </joint>
</robot>
